# build image 
# docker build -t feedback-app-node:dev --build-arg DEFAULT_PORT=8000 .

# run container
# docker run -p 3000:8000 -d -v feedback:/app/feedback -v "$(pwd):/app:ro" -v /app/node_modules -v /app/temp --name feedback-app --env-file ./.env --rm feedback-app-node:dev
