## Execute a command in a running container
# docker exec -it naughty_liskov npm init

## Override default container command 
# docker run -it node npm init

## append to ENTRYPOINT in Dockerfile
# docker run -it -v $(pwd):/app node-util:mynpm install express --save

## run a single service in a docker-compose file
# docker-compose run "npm" init 
