version: "3.8"

services: 
  server:
    # image: 'nginx:stable-alpine'
    build:
      # context: ./dockerfiles # Here we miss out ./nginx AND ./dockerfiles that is used in the nginx.dockerfile
      # dockerfile: nginx.dockerfile
      context: .
      dockerfile: dockerfiles/nignx.dockerfile # This is the correct way to do it
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # occassionally copy files from container to host
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html 
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14.15.4-alpine3.12
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html

