apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: story-pv
  storageClassName: standard
